Changing workflow dependencies

diff --git a/.github/workflows/main_only.yml b/.github/workflows/main_only.yml
--- a/.github/workflows/main_only.yml
+++ b/.github/workflows/main_only.yml
@@ -1,16 +1,53 @@
-# This should only trigger for changes to main
+# This should only trigger for changes to the staging branch
 
 # No need to run unit tests
-# How can we validate that the creds and infrastructure exist?
 
-name: Production only
+name: Production Only
 on:
   push:
     branches:
-      - master
+      - prod
+  pull_request:
+
+
 jobs:
-  main-only-job:
+  validate-secrets:
     runs-on: ubuntu-latest
+    environment: prod  # Set the `environment` key to use 
+
     steps:
-      - name: my-step
-        run: echo "Hello Production World!"
+
+      # Ensure that the expected secret is accessible
+      - name: Check if secret exists
+        env:
+          PRODUCTION_SECRET: ${{ secrets.PRODUCTION_SECRET }}
+        if: env.PRODUCTION_SECRET == null
+        run: |
+          echo "Error: Production Secret is inaccesible
+          exit 1
+
+      # Ensure that other env secrets are inaccessible
+      - name: Production secret
+        env:
+          PROD_SECRET: ${{ secrets.PROD_SECRET }}
+        if: env.PROD_SECRET == null
+        run: echo "Success! Product secret is inaccessible"
+
+  validate-infrastructure:
+    needs: validate-secrets
+    runs-on: ubuntu-latest
+    environment: prod
+    steps:
+      - name: Validate required infrastructure
+        run: echo "Running Python script to validate infra ..."
+
+  deploy-production:
+    needs: validate-infrastructure
+    runs-on: ubuntu-latest
+    environment: 
+      name: prod
+      url: https://prod.app.meetascent.com
+
+    steps:
+      - name: Deploy
+        run: echo "Deploying to production ..."
